namespace AspNetCoreSpa.Core.Enums
{
    public enum RankName
    {
        Väzeň,
        Batoľa,
        Dieťa,
        Pubertiak,
        Sluha,
        Učeň,
        Obchodník,
        Nezamestnaný,
        Priekupník,
        Podnikateľ,
        Bezdomovec,
        Zlodej,
        Mafián,
        Agent,
        Branec,
        Major,
        Pustovník,
        Mudrc,
        Závislák,
        Ombudsman,
        Ochranca_záQona,
        Kráľ,
        Správca,
        Šedá_eminencia
    }
}
